### ISSUE TITLE
Method sendResponse with undefined targetWindow

### ISSUE THREAD

**Issue by ghost** [microsoft/window-post-message-proxy#14]
The method sendResponse is called asynchronosly through an event, and eventually the targetWindow (the parent window that owns the iframe) could not exist.
So this ends with an unexpected error.

Two options:
- Check if the targetWindows exists
- Cancel the event subscription

**Comment by danielforwardcamp** [comment]
#15

**Comment by TomasLight** [comment]
The issue is still valid:
When user leaves a page with `onMessageReceived` handler, the `targetWindow` has destroyed before `sendResponse` is called.

Please apply supposed Pull request

**Comment by KotanaSai21** [comment]
This Issue has been fixed the latest version release `0.2.7.` 
Try Installing the latest version [windows-post-message-proxy-npm]( https://www.npmjs.com/package/window-post-message-proxy/v/0.2.7?activeTab=versions)
