### ISSUE TITLE
Not possible to validate origin

### ISSUE THREAD

**Issue by matt-hensley** [microsoft/window-post-message-proxy#5]
This library does not expose the `origin` field from incoming messages, making it impossible to validate.

See security recommendations for postMessage handling:
https://www.w3.org/TR/webmessaging/#authors

**Comment by leo-bo** [comment]
@ali-hamud could you comment on this? I have the same concerns as @barake.
Thanks!

**Comment by ayeshurun** [comment]
We closed the issue due to its age and inactivity.
